### PR TITLE
Added 'Written pitch' section and changed pitch to reference it

### PR DESCRIPTION
**Pull request by adrianholovaty**
This pull request references issue #4.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mnx/pull/148.html" title="Last updated on May 1, 2019, 2:12 PM UTC (d9a58af)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mnx/148/246e4c4...d9a58af.html" title="Last updated on May 1, 2019, 2:12 PM UTC (d9a58af)">Diff</a>

### CODE REVIEW

**Comment by clnoel** [comment]
I think we need to clarify how the new written-pitch interacts with key as well. For instance, if you are in G-major, do you spell an F# note as an F, and allow the active key or sounding-pitch to define the F#, or do you spell it as an F#?

**Comment by notator** [comment]
As per the instructions in Issue #150, the target of this PR should the gh-pages branch (not master).

**Comment by adrianholovaty** [comment]
@notator Turns out the commits do indeed need to be made on `master`, and they'll be carried over to `gh-pages` automatically. Apologies for the whiplashing here — I think we were all confused due to the fairly nebulous automated system. [See my comment here](https://github.com/w3c/mnx/issues/150#issuecomment-488256822) for more info.

**Comment by adrianholovaty** [comment]
@clnoel wrote:
> I think we need to clarify how the new written-pitch interacts with key as well. For instance, if you are in G-major, do you spell an F# note as an F, and allow the active key or sounding-pitch to define the F#, or do you spell it as an F#?

You'd spell it explicitly as an F#. I _think_ this is already handled by the spec, as it says: "The pitch attribute supplies the written pitch of the note as a chromatic pitch," and "chromatic pitch" is defined elsewhere in the document as a "diatonic step" plus "octave" plus "alteration".

With that said, do you think the spec should be clarified on that matter?

**Pull request merged**
