### PR TITLE
Implement <slur> as liaison content

### PR DESCRIPTION
**Pull request by adrianholovaty**
In this pull request, I've added a "Slurs" section to MNX-Common By Example page, and I've filled in the "Slurs" section of the spec.

As opposed to the [previous pull request](https://github.com/w3c/mnx/pull/159), this one defines a slur as "liaison content," per various discussion.

To view the By Example page as it stands on this branch:

https://cdn.githubraw.com/w3c/mnx/slurs-liaison/by-example/index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mnx/pull/169.html" title="Last updated on Jan 21, 2020, 4:50 PM UTC (52e2bac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mnx/169/4931ab4...52e2bac.html" title="Last updated on Jan 21, 2020, 4:50 PM UTC (52e2bac)">Diff</a>

### CODE REVIEW

**Comment by adrianholovaty** [comment]
This addresses issue #167.

**Comment by mscuthbert** [comment]
For a slur starting or ending on a chord -- must the slur go on the first note element (and the last note element)? What about multiple voices that begin together but then diverge -- are the notes in the middle covered by the slur or not?  (and if the default is the one, how will the other be specified).  I think that it's important that the specification not just give where a slur begins and ends but make it possible for playback and analysis software to easily discern if a note is covered by a slur or not.  (something that is often ambiguous even in standard notation)

I'm not 100% sure whether slurs are spanners or liasions -- I can really see arguments either way!

Great work so far!

**Comment by mscuthbert** [comment]
Must the end element be a note?  I have seen slurs that end on rests as well, and in contemporary music, both slurs and ties that that connect to nothing as a sort of l.v. or with an ornament

**Comment by adrianholovaty** [comment]
@mscuthbert wrote:
> For a slur starting or ending on a chord -- must the slur go on the first note element (and the last note element)?

Thanks for bringing this up. I've just added another example — “Slurs (for chords)” — in this branch. You can [view it here](https://cdn.githubraw.com/w3c/mnx/slurs-liaison/by-example/index.html). The upshot is that the `<slur>` gets added to the first `<note>` in the `<event>`. However, something about that smells weird to me, to be honest, and it makes me think a slur should link to an `<event>` instead of a `<note>` (more on this below)...

> What about multiple voices that begin together but then diverge -- are the notes in the middle covered by the slur or not? (and if the default is the one, how will the other be specified).

Mind posting an image that shows exactly what you mean? It doesn't need to be from published music; something contrived is totally fine. :)

> I think that it's important that the specification not just give where a slur begins and ends but make it possible for playback and analysis software to easily discern if a note is covered by a slur or not. (something that is often ambiguous even in standard notation)

Agreed. The solution here might be to provide some suggested algorithms for crawling through an MNX-Common file and determining which notes are covered by a given slur.

> Must the end element be a note? I have seen slurs that end on rests as well, and in contemporary music, both slurs and ties that that connect to nothing as a sort of l.v. or with an ornament

This is a great point. The spec says "liaison content" links to a `<note>` — so the direct answer to your question is "yes, it must be a note." Your counterexample of a slur ending on a rest makes me think that the slur's `target` should point at an `<event>` rather than a `<note>`. This would cover the case of a slur ending on a rest. I'll bring this up in our biweekly co-chairs meeting later today.

**Comment by bhamblok** [comment]
@adrianholovaty I would like to provide you an alternative technique to write down the examples source-code in the examples-pages.
When you encapsulate the sample-xml within a script-tag as follows, you don't have to transcribe the "<" and ">"-symbols into html-entities like ```&lt;``` ```&gt;``` which improves the readability of the source-code ;-)
```
<script type="application/xml" style="display: block; white-space: pre;">
  <mnx>
     <...>
  </mnx>
</script>
```

**Comment by adrianholovaty** [comment]
@bhamblok: Ooooh, I didn't know about that — thanks! What's the browser support like?

**Comment by bhamblok** [comment]
@adrianholovaty not sure... but, this is really basic usage of a script-tag and 2 css-props which are supported up to IE6 :-D

**Comment by adrianholovaty** [comment]
@bhamblok: Now that I think about it, I don't think this is feasible for us to use — because we embed some markup in the examples that highlights specific sections (`<div class="diff">` and `<div class="nodiff">`). If there's an elegant way to do this with `<script type="application/xml">`, let me know.

**Comment by bhamblok** [comment]
@adrianholovaty OK ... right ... I see.
But I think it might be worth experimenting to simply exchange
```<div class="diff> or <div class="nodiff">```
with
```<script type="application/xml" class="diff"> or <script type="application/xml" class="nodiff">```
And where you add the css-property "white-space: pre;" to the classes ".diff" and ".nodiff"...
I hope this works.

**Comment by adrianholovaty** [comment]
@bhamblok Ah, yes, I think that will work! I'm working on the change now — expect a commit soon. :)

**Comment by adrianholovaty** [comment]
@bhamblok That's now committed in 8dd67a711. Thanks again for the suggestion!

**Comment by cecilios** [comment]
Before closing this issue I think that it is important to clarify if it is mandatory that start and end points of an slur be on the same sequence.

This was suggested in issue 167 (https://github.com/w3c/mnx/issues/167#issuecomment-549413786) but open questions remained ( https://github.com/w3c/mnx/issues/167#issuecomment-549425188)

Later, in the comments to this PR it was also raised the question of how to determine the notes covered by an slur, and it was pointed that (see https://github.com/w3c/mnx/pull/169#issuecomment-558638486):
> Agreed. The solution here might be to provide some suggested algorithms for crawling through an MNX-Common file and determining which notes are covered by a given slur.

But I cannot find a reference to the constrain of start and end points of an slur be on the same sequence, or about any suggested algorithms for determining the notes affected by the slur. My apologies if a missed something.

**Comment by clnoel** [comment]
@cecilios I don't think we can do that. To my knowledge, sequences are within-measure only. Slurs can go across measures. If we were to identify a way to make sequences from different measures belong in the same "meta-sequence", we could make that restriction, and it would also solve the problem of identifying which notes in intervening measures belong to the slur.

--clnoel

**Comment by cecilios** [comment]
@clnoel Yes, you are right, sequences are within-measure only. I did not explain myself right , I tried to refer to sequences with the same voice attribute. But I'm not sure if forcing start and end notes of a slur having to be on the same voice is an acceptable constrain.

**Comment by cecilios** [comment]
Another issue in relation to this PR is the ordering of `<note>` and `<slur>` elements in the "Slurs (for chords)" example. According to current content model for the `<event>` element, slurs must go always after the notes.

The example for chords seems to suggest that for chords the slur must be defined before the notes, but I do not see the need for this, as according to current definition they always go attached to the event, and start/end notes, if required, are  can be specified using the start-note and end-note attributes.

**Pull request merged**
