### PR TITLE
Update examples and spec to use new beaming encoding

### PR DESCRIPTION
**Pull request by adrianholovaty**
This branch is not yet complete, but I'm creating the pull request so that it's easier to track the progress.

See also https://github.com/w3c/mnxconverter/pull/6

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mnx/pull/205.html" title="Last updated on Dec 8, 2020, 1:33 PM UTC (bb45357)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mnx/205/abf5502...bb45357.html" title="Last updated on Dec 8, 2020, 1:33 PM UTC (bb45357)">Diff</a>

### CODE REVIEW

**Comment by adrianholovaty** [comment]
I now consider this branch complete. The updates to MNX By Example are [viewable here](https://cdn.githubraw.com/w3c/mnx/beams-new/by-example/index.html).

**Comment by notator** [comment]
Thanks. The [Tuplets](https://cdn.githubraw.com/w3c/mnx/beams-new/by-example/index.html#tuplets) and [Parts](https://cdn.githubraw.com/w3c/mnx/beams-new/by-example/index.html#parts) examples also need to be updated for the new beaming encoding.

**Review by mdgood — APPROVED** [review]
This looks good to me.

**Comment by notator** [comment]
Both the `<event>` and `<note>` elements need to be given (are missing) an optional `id` attribute.

**Pull request merged**
